my-app/config/routes.rb
Rails.application.routes.draw do
  resources :sandwiches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

my-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my-app/app/models/sandwich.rb
class Sandwich < ApplicationRecord
end

my-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

my-app/app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
    before_action :find_sandwich, except: [:index, :new, :create]

    def index
        @sandwiches = Sandwich.all
    end

    def show
        @sandwich = Sandwich.find(params[:id])
    end

    def new
        @sandwich = Sandwich.new
    end

    def create
        Sandwich.create(sandwich_params)
        redirect_to sandwiches_path
    end

    def edit
    end

    def update
        @sandwich.update(sandwich_params)
        redirect_to @sandwich
    end

    def destroy
        @sandwich.destroy
        redirect_to sandwiches_path
    end

    private

    def find_sandwich
        @sandwich = Sandwich.find(params[:id])
    end

    def sandwich_params
        params.require(:sandwich).permit(:name, :spicyness, :vegetarian)
    end

end

my-app/app/helpers/application_helper.rb
module ApplicationHelper
end

my-app/app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

my-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
      <br>
      <%= render "sandwiches/nav" %>
    </footer>
  </body>
</html>

my-app/app/views/sandwiches/_form.html.erb
<%= form_for @sandwich do |f|%>
    <label for="name">Name:</label><br>
    <%= f.text_field :name %><br>
    <label for="Spicyness">Spicyness:</label><br>
    <%= f.number_field :spicyness %><br>
    <label for="Vegetarian">Vegetarian:</label><br>
    <%= check_box("sandwich", "vegetarian") %><br>
    <%= f.submit %>
<% end %>

my-app/app/views/sandwiches/_nav.html.erb
<h3>Navigation:</h3>
<%= link_to "See All Sandwiches", sandwiches_path %> | <%= link_to "Create A Sandwich", new_sandwich_path %>

my-app/app/views/sandwiches/edit.html.erb
<h1>Sandwich Editor</h1>
<%= render 'form' %>

my-app/app/views/sandwiches/index.html.erb
<h1>Welcome to Subwhey, the Sandwich Shoppe For Gains</h1>

<h3>Behold our 💪sandwiches</h3>
<ul>
<% @sandwiches.each do |sandwich|%>
    <li><%= link_to sandwich.name, sandwich %></li>
<% end %>
</ul>

my-app/app/views/sandwiches/new.html.erb
<h1>Sandwich Forger</h1>

<!--
<form action="/sandwiches" method="post">
  <label for="name">Name:</label><br>
  <input type="text" id="name" name="name" value=""><br>
  <label for="spicyness">Spicyness:</label><br>
  <input type="number" id="spicyness" name="spicyness" value=""><br>
  <label for="name">Vegetarian:</label><br>
  <input type="checkbox" id="vegetarian" name="vegetarian" value=""><br>
  <input type="submit" value="Forge">
</form>
-->

<%# How to comment out an ERB block:%>
<% if false %>
    <%= form_tag "/sandwiches" %>
    <label for="name">Name:</label><br>
    <%= text_field_tag "sandwich[name]" %><br>
    <label for="spicyness">Spicyness:</label><br>
    <%= number_field_tag "sandwich[spicyness]" %><br>
    <label for="checkbox">Vegetarian:</label><br>
    <%= check_box_tag "sandwich[vegetarian]" %><br>
    <%= submit_tag "Forge Sandwich" %>
<% end %>

<%= render 'form' %>

my-app/app/views/sandwiches/show.html.erb
<h1>Behold the <%= @sandwich.name %></h1>

<p>This sandwich is <%= @sandwich.vegetarian ? "fit for those who consume not the flesh" : "filled with slaughtered prey" %>.</p>

<p><%= "🌶" * @sandwich.spicyness %></p>

<%= link_to 'Edit Sandwich', edit_sandwich_path(@sandwich) %>
<br><br>
<%= button_to 'Delete', @sandwich, method: :delete %>